@startuml

left to right direction

actor Owner as o

package "owner site" {
    usecase "003_オーナーとしてログインする" as loginByOwner
    usecase "004_オーナーとしてログアウトする" as logoutByOwner
    usecase "005_ギルド参加者登録を依頼（仮登録）する" as requestCreateParticipant
    usecase "タスクを登録する" as createTaskByOwner
    usecase "タスクを更新する" as updateTaskByOwner
    usecase "タスクを削除する" as deleteTaskByOwner
    usecase "報酬を登録する" as createRewardByOwner
    usecase "インセンティブを登録する" as createIncentiveByOwner
    usecase "タスクの一覧を参照する" as listTaskByOwner
    usecase "条件に合致するタスクの一覧を参照する" as findTaskByOwner
    usecase "１タスクの詳細を参照する" as getTaskByOwner
    usecase "交渉記録を登録する" as createNegotiationRecordByOwner
    usecase "交渉記録を更新する" as updateNegotiationRecordByOwner
    usecase "交渉記録を参照する" as getNegotiationRecordByOwner
    usecase "タスクの内容を受諾する" as acceptTaskByOwner
}

o --> loginByOwner
o --> logoutByOwner
o --> requestCreateParticipant
o --> createTaskByOwner
o --> updateTaskByOwner
o --> deleteTaskByOwner
o --> createRewardByOwner
o --> createIncentiveByOwner
o --> listTaskByOwner
o --> findTaskByOwner
o --> getTaskByOwner
o --> createNegotiationRecordByOwner
o --> updateNegotiationRecordByOwner
o --> getNegotiationRecordByOwner
o --> acceptTaskByOwner

note left of requestCreateParticipant
・メールアドレスを入力
※入力されたメールアドレス宛に本登録用のURLを記載したメールが送信される。
end note

note left of updateTaskByOwner
・オーナーが登録したタスクを更新する。
end note

note left of acceptTaskByOwner
・参加者が登録したタスクに対して受諾する。
・受諾したタスクはロックされて編集不可になる。
・ロックされたタスクは参加者のToDoタスクとなる。
end note

@enduml
