package controller

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"

	"github.com/sky0621/familiagildo/adapter/controller/model"
)

// CreateNoticeByAdmin is the resolver for the createNoticeByAdmin field.
func (r *mutationResolver) CreateNoticeByAdmin(ctx context.Context, input model.NoticeInput) (*model.Notice, error) {
	panic(fmt.Errorf("not implemented: CreateNoticeByAdmin - createNoticeByAdmin"))
}
