package controller

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
)

// CreateGuildByAdmin is the resolver for the createGuildByAdmin field.
func (r *mutationResolver) CreateGuildByAdmin(ctx context.Context, input AdminGuildInput) (*Guild, error) {
	panic(fmt.Errorf("not implemented: CreateGuildByAdmin - createGuildByAdmin"))
}

// ListGuildByAdmin is the resolver for the listGuildByAdmin field.
func (r *queryResolver) ListGuildByAdmin(ctx context.Context) ([]*Guild, error) {
	panic(fmt.Errorf("not implemented: ListGuildByAdmin - listGuildByAdmin"))
}

// FindGuildByAdmin is the resolver for the findGuildByAdmin field.
func (r *queryResolver) FindGuildByAdmin(ctx context.Context, filter *AdminGuildFilter) ([]*Guild, error) {
	panic(fmt.Errorf("not implemented: FindGuildByAdmin - findGuildByAdmin"))
}

// GetGuildByAdmin is the resolver for the getGuildByAdmin field.
func (r *queryResolver) GetGuildByAdmin(ctx context.Context, id string) (*Guild, error) {
	panic(fmt.Errorf("not implemented: GetGuildByAdmin - getGuildByAdmin"))
}
