package controller

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
)

// CreateGuild is the resolver for the createGuild field.
func (r *mutationResolver) CreateGuild(ctx context.Context, task GuildInput) (*Guild, error) {
	panic(fmt.Errorf("not implemented: CreateGuild - createGuild"))
}

// FindGuild is the resolver for the findGuild field.
func (r *queryResolver) FindGuild(ctx context.Context) ([]*Guild, error) {
	panic(fmt.Errorf("not implemented: FindGuild - findGuild"))
}
