package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"

	"github.com/sky0621/kaubandus/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, task model.TaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: CreateTask - createTask"))
}

// FindTask is the resolver for the findTask field.
func (r *queryResolver) FindTask(ctx context.Context) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: FindTask - findTask"))
}
