// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/sky0621/familiagildo/adapter/controller"
	"github.com/sky0621/familiagildo/adapter/gateway"
	"github.com/sky0621/familiagildo/app"
	"github.com/sky0621/familiagildo/driver/db"
	"github.com/sky0621/familiagildo/driver/web"
	"github.com/sky0621/familiagildo/usecase"
)

// Injectors from wire.go:

func InitializeApp(dsn string, option app.DBSetOption, env app.Env, isTrace bool) (App, error) {
	client, err := db.NewQueries(dsn, option)
	if err != nil {
		return App{}, err
	}
	guildRepository := gateway.NewGuildRepository(client)
	guild := usecase.NewGuild(guildRepository)
	resolver := controller.NewResolver(guild)
	server, err := web.NewServer(env, isTrace, resolver)
	if err != nil {
		return App{}, err
	}
	setupApp := NewApp(client, server)
	return setupApp, nil
}
