// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type MutationResponse struct {
	ID *string `json:"id,omitempty"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// タスク
type Task struct {
	// ID
	ID string `json:"id"`
	// タスクの内容
	Content string `json:"Content"`
	// 報酬
	Reward string `json:"Reward"`
	// インセンティブ（よりよい成果をあげた場合の追加報酬）
	Incentive *string `json:"Incentive,omitempty"`
}

func (Task) IsNode()            {}
func (this Task) GetID() string { return this.ID }

// タスクインプット
type TaskInput struct {
	// タスクの内容
	Content string `json:"Content"`
	// 報酬
	Reward string `json:"Reward"`
	// インセンティブ（よりよい成果をあげた場合の追加報酬）
	Incentive *string `json:"Incentive,omitempty"`
}
