@startuml

left to right direction

actor Admin as a

package "admin site" {
    usecase "ギルドを登録する" as createGuildByAdmin
    usecase "ギルドの一覧を参照する" as listGuildByAdmin
    usecase "条件に合致するギルドの一覧を参照する" as findGuildByAdmin
    usecase "１ギルドの詳細を参照する" as getGuildByAdmin
    usecase "１ギルドのお知らせを登録する" as createNoticeByAdmin
}

a --> createGuildByAdmin
a --> listGuildByAdmin
a --> findGuildByAdmin
a --> getGuildByAdmin
a --> createNoticeByAdmin

note left of createGuildByAdmin
・保護者（メールアドレス）も登録する。
※入力されたメールアドレス宛に本登録用のURLを記載したメールが送信される。
end note

@enduml
