@startuml

[*] --> REGISTERING
REGISTERING --> [*]
REGISTERING : 仮登録

REGISTERING -> REGISTERED
REGISTERED --> [*]
REGISTERED : 登録済み

REGISTERED -> NEGOTIATING
NEGOTIATING -> REGISTERED
NEGOTIATING : 交渉中

NEGOTIATING -> ACCEPTED
ACCEPTED : 受諾済み

@enduml
