@startuml

left to right direction

actor Guest as g

package "guest site" {
    usecase "001_ギルド登録を依頼（仮登録）する" as requestCreateGuildByGuest
    usecase "002_ギルドを本登録する" as createGuildByGuest
    usecase "003_ギルド参加者を登録する" as createParticipantByGuest
}

g --> requestCreateGuildByGuest
g --> createGuildByGuest
g --> createParticipantByGuest

note left of requestCreateGuildByGuest
・メールアドレスを入力
※入力されたメールアドレス宛に本登録用のURLを記載したメールが送信される。
end note

note left of createGuildByGuest
・ログインID、パスワードを入力
end note

note left of createParticipantByGuest
・ログインID、パスワードを入力
end note

@enduml
