version: '3'

services:
  db:
    restart: always
    image: postgres:15-alpine
    container_name: familiagildo-container
    ports:
      - "11111:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=familiagildodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local/data:/docker-entrypoint-initdb.d/
  testdb:
    restart: always
    image: postgres:15-alpine
    container_name: familiagildo-test-container
    ports:
      - "11112:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=familiagildodbtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local_test/data:/docker-entrypoint-initdb.d/
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
