version: '3'

services:
  db:
    restart: always
    image: postgres:15-alpine
    container_name: kaubandus-container
    ports:
      - "11111:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=kaubandusdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local/data:/docker-entrypoint-initdb.d/
  testdb:
    restart: always
    image: postgres:15-alpine
    container_name: kaubandus-test-container
    ports:
      - "11112:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=kaubandusdbtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local_test/data:/docker-entrypoint-initdb.d/
