// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type Node interface {
	IsNode()
}

type MutationResponse struct {
	ID *string `json:"id"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

// タスク
type Task struct {
	// ID
	ID string `json:"id"`
	// タスクの内容
	Content string `json:"Content"`
	// 報酬
	Reward string `json:"Reward"`
	// インセンティブ（よりよい成果をあげた場合の追加報酬）
	Incentive *string `json:"Incentive"`
}

func (Task) IsNode() {}

// タスクインプット
type TaskInput struct {
	// タスクの内容
	Content string `json:"Content"`
	// 報酬
	Reward string `json:"Reward"`
	// インセンティブ（よりよい成果をあげた場合の追加報酬）
	Incentive *string `json:"Incentive"`
}
