@startuml

actor ゲスト as guest
participant メール内リンク as mail
boundary ギルド登録画面 as page1
boundary ギルド登録依頼画面 as page2
control "トークンAPI/チェック" as api1
database guest_token
database guild

guest -> mail:クリック
mail -> page1:トークン
page1 -> api1:ギルド登録依頼トークンチェック(トークン)
api1 -> guest_token:既存トークン取得(トークン)
note left:有効期限内
guest_token -> api1:トークン
alt do not have valid token
api1 -> page1:エラー
page1 -> page2:リダイレクト
end
api1 -> guild:仮登録済みギルド取得(ID)
guild -> api1:ギルド名
api1 -> page1:ギルドID、ギルド名、メールアドレス

@enduml