@startuml

actor ゲスト as guest
boundary ギルド登録FORM as page1
boundary ログインFORM as page2
control "ギルドAPI/本登録" as api
database guest_token
database guild
database owner
database guild_owner_relation as rel

guest -> page1:ギルド本登録
page1 -> api:ギルド本登録
note left
ギルド名
メールアドレス
ログインID
パスワード
オーナー名
トークン
end note
api -> guest_token:既存トークン取得(メールアドレス）
note left: 有効期限チェックなし
guest_token -> api:トークン(ギルドID)
alt do not have valid token
api -> page1:エラー
end
api -> api:トランザクション開始
api -> guild:ギルド更新(ギルド名、ステータス＝登録済み)
api -> api:パスワードハッシュ化
api -> owner:オーナー登録
note left
メールアドレス
オーナー名
ログインID
ハッシュ化パスワード
end note
api -> rel:ギルド・オーナー紐付け(ギルドID、オーナーID)
api -> guest_token:トークンレコード削除
api -> api:トランザクション終了
api -> page1
page1 -> page2:リダイレクト

@enduml