@startuml

actor ゲスト as guest
participant メール内リンク as mail
control ギルド登録依頼トークンチェックハンドラー as handler
boundary ギルドオーナー登録FORM as form
control ギルド本登録ハンドラー as handler2
boundary ログインFORM as form2
database guest_token
database guild
database owner
database guild_owner_relation as rel

guest -> mail:クリック
mail -> handler:トークン
handler -> guest_token:トークン
guest_token -> handler:有効期限
handler -> handler:トークン存在チェック、有効期限切れチェック
handler -> form:リダイレクト
form -> handler2:メールアドレス、表示名、ログインID、パスワード
handler2 -> guest_token:メールアドレス、表示名、トークン存在チェック
handler2 -> guest_token:レコード削除
handler2 -> guild:ステータス＝登録済み
handler2 -> handler2:パスワードハッシュ化
handler2 -> owner:メールアドレス、表示名、ログインID、ハッシュ化パスワード
handler2 -> rel:ギルドID、オーナーID
handler2 -> form2:リダイレクト

@enduml