@startuml

actor ゲスト as guest
boundary ギルド登録依頼FORM as form
control ギルド仮登録ハンドラー as handler
database guild
database guest_token
participant メール送信サービス as mail

guest -> form:ギルド登録を依頼
form -> handler:ギルド名、メールアドレス
handler -> guild:ギルド名、ステータス＝仮登録
guild -> handler:ギルドID
handler -> handler:トークン生成、有効期限決定
handler -> guest_token:メールアドレス、トークン、有効期限、ギルドID
handler -> mail:メールアドレス、トークン、有効期限
handler -> guest:受付番号

@enduml